language: php
php:
  - 7.0

git:
  depth: 5

sudo: false

env:
  global:
    secure: "o6mqwg0rKxTKqy1QJ5SttPCwB8kKa+2p5iynrxzeYEFIwAsPf+UfFYZyO6RqehDN2YjJzyz2YSnWP2Led/tKHz2obH+CmMuOr0qVaQ0j2BF3VnBb3mCZgISuQJFXPYHf+H/8iB2QgnocIetfAv60EcEghVlUtbVz3Ns9V0sXHJQEqsQNui1j41Mk5PDNyYCihXc7ksmWABaDdkPED5BNRpi7DVz3X6laiBd8BZrX13W4hu1adIvnUNCax9Ly+Vel/Ja00rNeyCMn+o8lG9FZdK4jWwaQgqiOBy8L+TQHKSqSEbiApdatb8s32ECtuDueBwqeMyKxJBlwVEytjlY2W7X3cW2EC37f0aKYSm9m+XdB4WdQf1vcYqfXi/Z8zOHKfJgI7BSoaksYy4JcLZLxcnGtLQp4+97vlCWOaJXh+5C7FvWqvUqyshE8NJRRZ7WiZdtwsgpRGtSR0nmQbq+5wBgpEILWdeeowYcrA+kKDSbfW1FbE57LnAPTXu4Ywm4jUTtx31hQ+E9RGzBiFk4kFlVc691wDgvujjx7EqTD7/e/NUYsiwetGAs4F4ofHphw6pX+2HjMZBDQDcpMMLpHwA0SiIKJYFY95qn1T811BaV2iQcGMwwiDaFPegYSDBQHAsubhqxpO/K0tc5JZX/XZOQ6jS2XGlphiSAuTokUPxI="

matrix:
  fast_finish: true

before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer test
  - composer cs-check
after_script:
  - composer upload-coverage
